services:
  postgres:
    image: postgres:16
    container_name: udam-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped