[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "udam-sdk"
version = "0.1.0"
dependencies = ["requests>=2.31.0"]
requires-python = ">=3.8"

[tool.setuptools]
py-modules = ["udam_client"]
